# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tk5gzeDpw_qoNgjl1SC0XENCAD7XRKTM
"""

# Cell 1 — Install all libraries
!pip install langchain langchain-community langchain-groq
!pip install sentence-transformers faiss-cpu rank-bm25
!pip install pypdf fastapi uvicorn nest-asyncio pyngrok python-docx
!pip install duckduckgo-search

# Cell 2 — API Keys
import os
os.environ["GROQ_API_KEY"] = "your_groq_api_key_here"

# Cell — Universal File Reader (PDF + DOCX + TXT)

from google.colab import files
import os

# Upload file
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

text_data = []

# Get file extension
ext = file_name.split(".")[-1].lower()

# ---------------- PDF ----------------
if ext == "pdf":
    from pypdf import PdfReader

    reader = PdfReader(file_name)

    for i, page in enumerate(reader.pages):
        text = page.extract_text()
        if text:
            text_data.append({
                "text": text,
                "page": i+1,
                "file": file_name
            })

    print(f"✅ PDF Extracted: {len(text_data)} pages")

# ---------------- DOCX ----------------
elif ext == "docx":
    from docx import Document

    doc = Document(file_name)

    for i, para in enumerate(doc.paragraphs):
        if para.text.strip():
            text_data.append({
                "text": para.text,
                "paragraph": i+1,
                "file": file_name
            })

    print(f"✅ DOCX Extracted: {len(text_data)} paragraphs")

# ---------------- TXT ----------------
elif ext == "txt":
    with open(file_name, "r", encoding="utf-8") as f:
        content = f.read()

    text_data.append({
        "text": content,
        "file": file_name
    })

    print("✅ TXT Extracted")

# ---------------- Unsupported ----------------
else:
    print("❌ Unsupported file type!")

# Preview output
print("\n--- Sample Output ---")
print(text_data[:2])

# Cell — Smart Chunking (Optimized for RAG)

def chunk_text(data_items, chunk_size=700, overlap=120):
    chunks = []

    for item in data_items:
        text = item["text"]

        # source info (page or paragraph)
        identifier = item.get("page", item.get("paragraph", None))
        file_name = item["file"]

        start = 0

        while start < len(text):
            end = start + chunk_size
            chunk = text[start:end]

            # store chunk with metadata
            chunks.append({
                "text": chunk,
                "source_id": identifier,
                "source_file": file_name
            })

            start += chunk_size - overlap

    return chunks


# Run chunking
chunks = chunk_text(text_data)

print(f"✅ Created {len(chunks)} smart chunks")

# Cell 6 — Embeddings (FREE model)
from sentence_transformers import SentenceTransformer
import numpy as np, faiss

embed_model = SentenceTransformer("all-MiniLM-L6-v2")

texts = [c["text"] for c in chunks]
embeddings = embed_model.encode(texts, show_progress_bar=True)

# Build FAISS index
dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(np.array(embeddings, dtype="float32"))
print(f"✅ FAISS index built with {index.ntotal} vectors")

# Cell 7 — BM25 Keyword Search
from rank_bm25 import BM25Okapi

tokenized = [t.lower().split() for t in texts]
bm25 = BM25Okapi(tokenized)
print("✅ BM25 index ready")

# Cell 8 — Hybrid Search function
def hybrid_search(query, top_k=5):
    # Semantic search (FAISS)
    q_embed = embed_model.encode([query])
    D, I = index.search(np.array(q_embed, dtype="float32"), top_k)
    semantic_results = [chunks[i] for i in I[0]]

    # Keyword search (BM25)
    scores = bm25.get_scores(query.lower().split())
    bm25_top = np.argsort(scores)[::-1][:top_k]
    keyword_results = [chunks[i] for i in bm25_top]

    # Merge (deduplicate)
    seen, merged = set(), []
    for c in semantic_results + keyword_results:
        key = c["text"][:50]
        if key not in seen:
            seen.add(key)
            merged.append(c)
    return merged[:top_k]

# Test it
results = hybrid_search("what is machine learning")
print(f"✅ Found {len(results)} relevant chunks")

# Cell 9 — Agent Router logic
import re

def detect_intent(query):
    query_lower = query.lower()

    # Math detection
    if re.search(r'[\d]+[\s]*[\+\-\*\/\^%][\s]*[\d]+', query):
        return "calculator"
    if any(w in query_lower for w in ["calculate", "compute", "math", "how much is", "what is", "equals"]):
        if re.search(r'\d', query):
            return "calculator"

    # Web search detection
    web_keywords = ["latest", "news", "today", "current", "2024", "2025", "recent", "who won", "price of"]
    if any(w in query_lower for w in web_keywords):
        return "web_search"

    # PDF detection
    return "pdf_rag"  # default

# Test
print(detect_intent("25 * 4 + 10"))       # calculator
print(detect_intent("latest AI news"))     # web_search
print(detect_intent("what is deep learning"))  # pdf_rag

# Cell 10 — Calculator Tool
def calculator_tool(query):
    try:
        # Extract math expression safely
        expr = re.findall(r'[\d\s\+\-\*\/\.\(\)\^%]+', query)
        if expr:
            result = eval(expr[0].strip())
            return f"Result: {result}"
        return "Could not find math expression."
    except:
        return "Math error."

# Cell 11 — Web Search Tool (FREE, no API key)
from duckduckgo_search import DDGS

def web_search_tool(query, max_results=3):
    with DDGS() as ddgs:
        results = list(ddgs.text(query, max_results=max_results))
    if not results:
        return "No results found."
    output = ""
    for r in results:
        output += f"Title: {r['title']}\nSummary: {r['body']}\n\n"
    return output

# Cell 12 — Groq LLM (FREE)
from langchain_groq import ChatGroq

llm = ChatGroq(model="llama3-8b-8192", temperature=0)

def ask_llm(question, context=""):
    prompt = f"""You are a helpful AI assistant.
Context: {context}

Question: {question}
Answer clearly and concisely."""
    response = llm.invoke(prompt)
    return response.content

# Cell 13 — Full Working Agent

def agent(query):
    try:
        intent = detect_intent(query)
        print(f"🔍 Intent detected: {intent}")

        # ---------------- Calculator ----------------
        if intent == "calculator":
            return calculator_tool(query)

        # ---------------- Web Search ----------------
        elif intent == "web_search":
            web_results = web_search_tool(query)

            if isinstance(web_results, list):
                web_results = "\n".join([str(r) for r in web_results])

            return ask_llm(query, context=web_results)

        # ---------------- PDF RAG ----------------
        else:
            chunks_found = hybrid_search(query)

            if not chunks_found:
                return "❌ No relevant documents found."

            context = "\n".join([c.get("text", "") for c in chunks_found])

            sources = []
            for c in chunks_found:
                page = c.get("page", None)
                if page:
                    sources.append(f"Page {page}")
                else:
                    sources.append("Unknown Source")

            answer = ask_llm(query, context=context)

            return f"{answer}\n\n📄 Sources: {', '.join(sources)}"

    except Exception as e:
        return f"❌ Error: {str(e)}"


# ---------------- TEST ----------------
print(agent("What is machine learning?"))
print(agent("25 * 4 + 10"))
print(agent("latest AI news today"))

# Cell 14 — FastAPI server inside Colab
import nest_asyncio
from fastapi import FastAPI, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
import uvicorn, threading

nest_asyncio.apply()

app = FastAPI()
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

@app.post("/chat")
async def chat(data: dict):
    query = data.get("question", "")
    answer = agent(query)
    return {"answer": answer}

@app.post("/upload")
async def upload(file: UploadFile = File(...)):
    content = await file.read()
    # process PDF here (same as Phase 2)
    return {"status": "uploaded", "filename": file.filename}

# Run server
def run():
    uvicorn.run(app, host="0.0.0.0", port=8000)

thread = threading.Thread(target=run, daemon=True)
thread.start()
print("✅ Server running on port 8000")

!npx create-react-app ai-agent-ui
!cd ai-agent-ui
!npm install axios

npm install -g vercel
vercel deploy